#!/bin/bash
#
#	/etc/rc.d/init.d/sobreirisd
#
# Starts the SobreIRIS daemon
#
# chkconfig: 345 80 26
# description: Listen and dispatch whois queries
# processname: sobreiris

# Source function library.
. /etc/rc.d/init.d/functions


perl="/usr/bin/perl";
binary="/usr/local/bin/SobreIRIS"

[ -x $binary ] || exit 0

[ -x $perl ] || exit 0


RETVAL=0

#
# See how we were called.
#

start() {
	# Check if it is already running
	if [ ! -f /var/lock/subsys/sobreiris ]; then
	    echo -n $"Starting sobreiris  daemon: "
	    $binary
	    RETVAL=$?
	    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/sobreiris
	    echo
	fi
	return $RETVAL
}

stop() {
	echo -n $"Stopping sobreiris daemon: "
	killproc -p /var/run/sobreiris.pid
	RETVAL=$?
	echo
	if [ $RETVAL -eq 0 ]; then 
	 	rm -f /var/lock/subsys/sobreiris
		rm -f /var/run/sobreiris.pid
	fi
        return $RETVAL
}


restart() {
	stop
	start
}	

reload() {
	trap "" SIGHUP
	killall -HUP SobreIRIS
}	

case "$1" in
start)
	start
	;;
stop)
	stop
	;;
reload)
	reload
	;;
restart)
	restart
	;;
condrestart)
	if [ -f /var/lock/subsys/acpid ]; then
	    restart
	fi
	;;
status)
	status acpid
	;;
*)
	echo $"Usage: $0 {start|stop|status|restart|condrestart|reload}"
	exit 1
esac

exit $RETVAL
